name: Docker, Build & Test (Go)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-go-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t my-go-app:test .

    - name: Run Go application inside Docker container
      run: |
        docker run --rm my-go-app:test go run main.go

    - name: Run Go tests inside Docker container
      run: |
        docker run --rm my-go-app:test go test -v ./...
