name: Docker, Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t my-python-app:test .

    - name: Run tests inside Docker container
      run: |
        docker run --rm my-python-app:test pytest test.py
